@startuml
participant Actor
Actor -> BuyProductServlet : doGet
activate BuyProductServlet
create GetOnlineOrderByIdDatabase
BuyProductServlet -> GetOnlineOrderByIdDatabase : new
activate GetOnlineOrderByIdDatabase
GetOnlineOrderByIdDatabase --> BuyProductServlet
deactivate GetOnlineOrderByIdDatabase
create CheckIfCanBeCreatedOnlineInvoiceDatabase
BuyProductServlet -> CheckIfCanBeCreatedOnlineInvoiceDatabase : new
activate CheckIfCanBeCreatedOnlineInvoiceDatabase
CheckIfCanBeCreatedOnlineInvoiceDatabase --> BuyProductServlet
deactivate CheckIfCanBeCreatedOnlineInvoiceDatabase
BuyProductServlet -> CheckIfCanBeCreatedOnlineInvoiceDatabase : checkIfCanBeCreatedOnlineInvoice
activate CheckIfCanBeCreatedOnlineInvoiceDatabase
CheckIfCanBeCreatedOnlineInvoiceDatabase --> BuyProductServlet
deactivate CheckIfCanBeCreatedOnlineInvoiceDatabase
BuyProductServlet -> AbstractServlet : writeResource
activate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create OutOfStock
BuyProductServlet -> OutOfStock : new
activate OutOfStock
create ErrorMessage
OutOfStock -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> OutOfStock
deactivate ErrorMessage
OutOfStock --> BuyProductServlet
deactivate OutOfStock
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> GenericError : toJSON
activate GenericError
GenericError --> AbstractServlet
deactivate GenericError
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create SqlInternalError
BuyProductServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> BuyProductServlet
deactivate SqlInternalError
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create IncorrectlyFormattedDataError
BuyProductServlet -> IncorrectlyFormattedDataError : new
activate IncorrectlyFormattedDataError
create ErrorMessage
IncorrectlyFormattedDataError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> IncorrectlyFormattedDataError
deactivate ErrorMessage
IncorrectlyFormattedDataError --> BuyProductServlet
deactivate IncorrectlyFormattedDataError
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create GetOnlineInvoiceFromOrderDatabase
BuyProductServlet -> GetOnlineInvoiceFromOrderDatabase : new
activate GetOnlineInvoiceFromOrderDatabase
GetOnlineInvoiceFromOrderDatabase --> BuyProductServlet
deactivate GetOnlineInvoiceFromOrderDatabase
BuyProductServlet -> AbstractServlet : writeResource
activate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create GetOnlineOrderByIdDatabase
BuyProductServlet -> GetOnlineOrderByIdDatabase : new
activate GetOnlineOrderByIdDatabase
GetOnlineOrderByIdDatabase --> BuyProductServlet
deactivate GetOnlineOrderByIdDatabase
create CheckIfCanBeCreatedOnlineInvoiceDatabase
BuyProductServlet -> CheckIfCanBeCreatedOnlineInvoiceDatabase : new
activate CheckIfCanBeCreatedOnlineInvoiceDatabase
CheckIfCanBeCreatedOnlineInvoiceDatabase --> BuyProductServlet
deactivate CheckIfCanBeCreatedOnlineInvoiceDatabase
BuyProductServlet -> CheckIfCanBeCreatedOnlineInvoiceDatabase : checkIfCanBeCreatedOnlineInvoice
activate CheckIfCanBeCreatedOnlineInvoiceDatabase
CheckIfCanBeCreatedOnlineInvoiceDatabase --> BuyProductServlet
deactivate CheckIfCanBeCreatedOnlineInvoiceDatabase
BuyProductServlet -> AbstractServlet : writeResource
activate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create OutOfStock
BuyProductServlet -> OutOfStock : new
activate OutOfStock
create ErrorMessage
OutOfStock -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> OutOfStock
deactivate ErrorMessage
OutOfStock --> BuyProductServlet
deactivate OutOfStock
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create SqlInternalError
BuyProductServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> BuyProductServlet
deactivate SqlInternalError
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create IncorrectlyFormattedDataError
BuyProductServlet -> IncorrectlyFormattedDataError : new
activate IncorrectlyFormattedDataError
create ErrorMessage
IncorrectlyFormattedDataError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> IncorrectlyFormattedDataError
deactivate ErrorMessage
IncorrectlyFormattedDataError --> BuyProductServlet
deactivate IncorrectlyFormattedDataError
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create GetOnlineOrderByIdDatabase
BuyProductServlet -> GetOnlineOrderByIdDatabase : new
activate GetOnlineOrderByIdDatabase
GetOnlineOrderByIdDatabase --> BuyProductServlet
deactivate GetOnlineOrderByIdDatabase
BuyProductServlet -> AbstractServlet : writeResource
activate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create CancelOrderError
BuyProductServlet -> CancelOrderError : new
activate CancelOrderError
create ErrorMessage
CancelOrderError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> CancelOrderError
deactivate ErrorMessage
CancelOrderError --> BuyProductServlet
deactivate CancelOrderError
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create SqlInternalError
BuyProductServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> BuyProductServlet
deactivate SqlInternalError
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
create IncorrectlyFormattedPathError
BuyProductServlet -> IncorrectlyFormattedPathError : new
activate IncorrectlyFormattedPathError
create ErrorMessage
IncorrectlyFormattedPathError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> IncorrectlyFormattedPathError
deactivate ErrorMessage
IncorrectlyFormattedPathError --> BuyProductServlet
deactivate IncorrectlyFormattedPathError
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
BuyProductServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> GenericError : toJSON
activate GenericError
GenericError --> AbstractServlet
deactivate GenericError
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> BuyProductServlet
deactivate AbstractServlet
return
@enduml