@startuml
participant Actor
Actor -> LoginServlet : doGet
activate LoginServlet
create Message
LoginServlet -> Message : new
activate Message
Message --> LoginServlet
deactivate Message
LoginServlet -> AbstractServlet : writeMessageOrRedirect
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> LoginServlet
deactivate AbstractServlet
LoginServlet -> AbstractServlet : writeJsp
activate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> LoginServlet
deactivate AbstractServlet
create Message
LoginServlet -> Message : new
activate Message
Message --> LoginServlet
deactivate Message
LoginServlet -> AbstractServlet : writeMessageOrRedirect
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> LoginServlet
deactivate AbstractServlet
create Message
LoginServlet -> Message : new
activate Message
Message --> LoginServlet
deactivate Message
LoginServlet -> AbstractServlet : writeMessageOrRedirect
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> LoginServlet
deactivate AbstractServlet
LoginServlet -> AbstractServlet : writeJsp
activate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> LoginServlet
deactivate AbstractServlet
LoginServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> GenericError : toJSON
activate GenericError
GenericError --> AbstractServlet
deactivate GenericError
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> LoginServlet
deactivate AbstractServlet
return
@enduml