@startuml
participant Actor
Actor -> UserServlet : doPost
activate UserServlet
create Customer
UserServlet -> Customer : new
activate Customer
Customer --> UserServlet
deactivate Customer
create UpdateCustomerDatabase
UserServlet -> UpdateCustomerDatabase : new
activate UpdateCustomerDatabase
UpdateCustomerDatabase --> UserServlet
deactivate UpdateCustomerDatabase
UserServlet -> UpdateCustomerDatabase : updateCustomer
activate UpdateCustomerDatabase
create Customer
UpdateCustomerDatabase -> Customer : new
activate Customer
Customer --> UpdateCustomerDatabase
deactivate Customer
UpdateCustomerDatabase --> UserServlet
deactivate UpdateCustomerDatabase
create SqlInternalError
UserServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> UserServlet
deactivate SqlInternalError
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> GenericError : toJSON
activate GenericError
GenericError --> AbstractServlet
deactivate GenericError
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
UserServlet -> AbstractServlet : writeResource
activate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
create GetEmployeeDatabase
UserServlet -> GetEmployeeDatabase : new
activate GetEmployeeDatabase
GetEmployeeDatabase --> UserServlet
deactivate GetEmployeeDatabase
create Employee
UserServlet -> Employee : new
activate Employee
Employee --> UserServlet
deactivate Employee
create Role
UserServlet -> Role : new
activate Role
Role --> UserServlet
deactivate Role
create Employee
UserServlet -> Employee : new
activate Employee
Employee --> UserServlet
deactivate Employee
create UpdateEmployeeDatabase
UserServlet -> UpdateEmployeeDatabase : new
activate UpdateEmployeeDatabase
UpdateEmployeeDatabase --> UserServlet
deactivate UpdateEmployeeDatabase
UserServlet -> UpdateEmployeeDatabase : updateEmployee
activate UpdateEmployeeDatabase
create Role
UpdateEmployeeDatabase -> Role : new
activate Role
Role --> UpdateEmployeeDatabase
deactivate Role
create Employee
UpdateEmployeeDatabase -> Employee : new
activate Employee
Employee --> UpdateEmployeeDatabase
deactivate Employee
UpdateEmployeeDatabase --> UserServlet
deactivate UpdateEmployeeDatabase
UserServlet -> AbstractServlet : writeResource
activate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
create SqlInternalError
UserServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> UserServlet
deactivate SqlInternalError
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> GenericError : toJSON
activate GenericError
GenericError --> AbstractServlet
deactivate GenericError
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
create UpdatePasswordCustomerDatabase
UserServlet -> UpdatePasswordCustomerDatabase : new
activate UpdatePasswordCustomerDatabase
UpdatePasswordCustomerDatabase --> UserServlet
deactivate UpdatePasswordCustomerDatabase
UserServlet -> UpdatePasswordCustomerDatabase : updatePassword
activate UpdatePasswordCustomerDatabase
UpdatePasswordCustomerDatabase --> UserServlet
deactivate UpdatePasswordCustomerDatabase
create ChangePasswordError
UserServlet -> ChangePasswordError : new
activate ChangePasswordError
create ErrorMessage
ChangePasswordError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> ChangePasswordError
deactivate ErrorMessage
ChangePasswordError --> UserServlet
deactivate ChangePasswordError
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
create Message
UserServlet -> Message : new
activate Message
Message --> UserServlet
deactivate Message
UserServlet -> AbstractServlet : writeResource
activate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
create SqlInternalError
UserServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> UserServlet
deactivate SqlInternalError
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
create UpdatePasswordEmployeeDatabase
UserServlet -> UpdatePasswordEmployeeDatabase : new
activate UpdatePasswordEmployeeDatabase
UpdatePasswordEmployeeDatabase --> UserServlet
deactivate UpdatePasswordEmployeeDatabase
UserServlet -> UpdatePasswordEmployeeDatabase : updatePassword
activate UpdatePasswordEmployeeDatabase
UpdatePasswordEmployeeDatabase --> UserServlet
deactivate UpdatePasswordEmployeeDatabase
create ChangePasswordError
UserServlet -> ChangePasswordError : new
activate ChangePasswordError
create ErrorMessage
ChangePasswordError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> ChangePasswordError
deactivate ErrorMessage
ChangePasswordError --> UserServlet
deactivate ChangePasswordError
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
create Message
UserServlet -> Message : new
activate Message
Message --> UserServlet
deactivate Message
UserServlet -> AbstractServlet : writeResource
activate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> Resource : toJSON
activate Resource
Resource --> AbstractServlet
deactivate Resource
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create ListProductCategoryDatabase
AbstractServlet -> ListProductCategoryDatabase : new
activate ListProductCategoryDatabase
ListProductCategoryDatabase --> AbstractServlet
deactivate ListProductCategoryDatabase
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet -> AbstractServlet : decapitalize
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
create SqlInternalError
AbstractServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> AbstractServlet
deactivate SqlInternalError
AbstractServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
create SqlInternalError
UserServlet -> SqlInternalError : new
activate SqlInternalError
create ErrorMessage
SqlInternalError -> ErrorMessage : new
activate ErrorMessage
create Message
ErrorMessage -> Message : new
activate Message
Message --> ErrorMessage
deactivate Message
ErrorMessage --> SqlInternalError
deactivate ErrorMessage
SqlInternalError --> UserServlet
deactivate SqlInternalError
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> Message : toJSON
activate Message
Message --> AbstractServlet
deactivate Message
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> GenericError : toJSON
activate GenericError
GenericError --> AbstractServlet
deactivate GenericError
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> GenericError : toJSON
activate GenericError
GenericError --> AbstractServlet
deactivate GenericError
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
UserServlet -> AbstractServlet : writeError
activate AbstractServlet
AbstractServlet -> GenericError : toJSON
activate GenericError
GenericError --> AbstractServlet
deactivate GenericError
AbstractServlet -> AbstractServlet : writeJSON
activate AbstractServlet
AbstractServlet --> AbstractServlet
deactivate AbstractServlet
AbstractServlet --> UserServlet
deactivate AbstractServlet
return
@enduml